CONTIKI_PROJECT = example_uart_master example_uart_slave
all: $(CONTIKI_PROJECT)
CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

#UIP_CONF_IPV6=1

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include